### ISSUE TITLE
DOC How to get the `conda` command?

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/bluesky_training#106]
[Create the conda environment](https://bcda-aps.github.io/bluesky_training/instrument/_install_new_instrument.html#create-the-conda-environment) does not describe how to get the `conda` command (either activate a conda environment or some other method).  APS-specific advice should be provided.  Maybe it's already written somewhere else?

**Comment by rodolakis** [comment]
I can take that one. I finally got my new laptop and will need to go through the installation again.

**Comment by rodolakis** [comment]
Goes with https://github.com/BCDA-APS/bluesky_training/issues/104
