### ISSUE TITLE
DOC conda details should move to reference

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/bluesky_training#119]
The document titled [_Conda virtual environment_](https://bcda-aps.github.io/bluesky_training/instrument/_conda_environment.html) seems out of place in the `instrument/` directory.  There is a companion document titled [_Conda Base Environment_](https://bcda-aps.github.io/bluesky_training/reference/_conda_base.html) in `reference`.

These documents are linked from others.  The edit will involve more than just one file.  Maybe combine these two?

**Comment by rodolakis** [comment]
Agree, the details about conda belongs to reference rather than instrument. I can take that one.
