### ISSUE TITLE
DOC Hello world notebook has extra cells in documentation

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/bluesky_training#129]
![image](https://github.com/BCDA-APS/bluesky_training/assets/2279984/387cb99e-7188-4c42-a6fe-491cf45b2190)

**Comment by prjemian** [comment]
Seems to be a common problem for all notebooks.

**Comment by prjemian** [comment]
I can replicate this behavior in a local build.

**Comment by prjemian** [comment]
In the editor:
![image](https://github.com/BCDA-APS/bluesky_training/assets/2279984/b849f375-8627-4a80-b277-9b995d1e225b)


After rebuilding the docs, here's the view in the browser:
![image](https://github.com/BCDA-APS/bluesky_training/assets/2279984/58796ebd-3e30-476a-9ae1-7868f8435691)

**Comment by prjemian** [comment]
Which uses this HTML code:

```html
<p>What about extra cells?</p>
<div class="nbinput docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[1]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre><span></span><span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Hello&quot;</span><span class="p">)</span>
</pre></div>
</div>
</div>
<div class="nboutput nblast docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>
Hello
</pre></div></div>
</div>
```

**Comment by prjemian** [comment]
This `div` block is responsible: `nbinput docutils container`

[nbsphinx](https://nbsphinx.readthedocs.io/en/0.9.2/)

**Comment by prjemian** [comment]
Apparently, the order of listing the Sphinx extensions is important.  Problem goes away when this one is moved to the end of the list: https://github.com/BCDA-APS/bluesky_training/blob/9bc5b9e83bddbb46fbc4af02bc82767afaf08c4f/docs/source/conf.py#L27

**Comment by prjemian** [comment]
![image](https://github.com/BCDA-APS/bluesky_training/assets/2279984/1b4aae4c-facc-4552-a912-309cacaed91c)
