### ISSUE TITLE
DOC git advice for the reference section

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/bluesky_training#131]
With a new account, the default git user and email are not set.  These are the [steps](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address):

```bash
git config --global user.name "Lynn User"
git config --global user.email "YOUR_EMAIL"
```

At the same time, extend the interval when you don't have to retype your github [credentials](https://git-scm.com/docs/git-credential-cache) (a 1 hour period is shown):

```bash
git config credential.helper 'cache --timeout=3600'
```

**Comment by prjemian** [comment]
Seems to be a FAQ.

**Comment by prjemian** [comment]
Also for the git help document.

**Comment by rodolakis** [comment]
> With a new account, the default git user and email are not set. These are the [steps](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address):
> 
> ```shell
> git config --global user.name "Lynn User"
> git config --global user.email "YOUR_EMAIL"
> ```

The error message for this is very straightforward, give you those exact instructions. I don't think we need to explain this. Users should be able to handle it? (it is also easy to find the answer on google)

**Comment by rodolakis** [comment]
> At the same time, extend the interval when you don't have to retype your github [credentials](https://git-scm.com/docs/git-credential-cache) (a 1 hour period is shown):
> 
> ```shell
> git config credential.helper 'cache --timeout=3600'
> ```

SSH keys allow you to establish a secure connection between your computer and GitLab/Hub, so you never have to authenticate. I am thinking that authentification preferences might be outside of the scope of our documentation?
