### ISSUE TITLE
DOC _testing.md

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/bluesky_training#139]
Name is not very meaningful. 
Contain both:
- ophyd testing with S:SRcurrentAI => redundant with _test_bluesky_at_APS.md
- APS data management   => could be a separate file (not every beamline are setup for the DM system)
I want to re-purpose _testing.md to only address the APS data management, and merge the ophyd part with _test_bluesky_at_APS.md

**Comment by prjemian** [comment]
OK.  These document was intended to test during the installation process, that certain software packages were installed and function as expected.  The entire content of this file could be relocated.

**Comment by rodolakis** [comment]
Re-purpose to APS data management system only, and relocated to reference
