### ISSUE TITLE
DOC update blueskyStarter.sh

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/bluesky_training#142]
From - #127:

Needed to edit the blueskyStarter.sh file.

- Specific changes in the new repo: https://github.com/APS-1ID-MPE/hexm-bluesky/commit/f71495c9fa68e48b43e6b2431bc64763b2c270ca
- must be executable: chmod +x blueskyStarter.sh

**Comment by prjemian** [comment]
Drop the micromamba parts

**Comment by prjemian** [comment]
Note that `blueskyStarter.sh` is marked executable in the repo.  The `new_bluesky_instrument.py` installer should preserve this.  Same for `qserver.sh`

**Comment by prjemian** [comment]
Needs a `.gitignore` file
