### ISSUE TITLE
DOC apply tabs to location-dependent instructions

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/bluesky_training#201]
This [section](https://bcda-aps.github.io/bluesky_training/reference/_create_conda_env.html#activate-conda) would benefit from re-formatting the instructions into tabbed choices: APS only, non-APS similar to what is done in other sections.

**Comment by rodolakis** [comment]
Yes we talked about it a while back. It requires to go from .md to .rst, which I did not have the time to do then. That seems like a nice way for me to get back to where I left my documentation review project.
