### ISSUE TITLE
duplicate code section in Basic, Part B Motor and Move tutorial in APS Bluesky training documentation

### ISSUE THREAD

**Issue by lcgallington** [BCDA-APS/bluesky_training#266]
Not so much a bug as in an unintentional duplication of code.  Code inputs 9-16 for the Basic Part B tutorial are an exact duplicate of code inputs 1-8--maybe someone pasted stuff twice by mistake?
https://bcda-aps.github.io/bluesky_training/tutor/_basic_b.html

**Comment by prjemian** [comment]
Ya caught me at it!  Thanks.
