### ISSUE TITLE
DOC: how to run a time scan?

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/bluesky_training#325]
@jilavsky asks (by email):

> ... need to collect few 1000 points at 0.05sec on my scaler to check noise. Is it some version of `bp.scan`?

**Comment by prjemian** [comment]
Good question.  Seems as if this should be in the HOWTO section.

`bp.count([scaler], num=1000, delay=0.05)`

Be sure to set the `scaler.preset_time.put(0.01)` (command-line use) such that it does not increase your 0.05s acquisition period.

**Comment by prjemian** [comment]
### example

```py
In [1]: scaler1.preset_time.put(0.2)

In [2]: RE(bp.count([scaler1], num=5, delay=1))


Transient Scan ID: 24     Time: 2024-10-30 09:51:43
Persistent Unique Scan ID: 'b08df7db-5705-45c5-8e50-e528ad92cacc'
New stream: 'label_start_motor'
New stream: 'primary'
+-----------+------------+------------+------------+------------+------------+------------+------------+
|   seq_num |       time |      clock |         I0 |      scint |      diode |       I000 |        I00 |
+-----------+------------+------------+------------+------------+------------+------------+------------+
|         1 | 09:51:43.5 |    3000000 |          1 |          1 |          1 |          1 |          1 |
|         2 | 09:51:44.5 |    3000000 |          2 |          1 |          1 |          0 |          1 |
|         3 | 09:51:45.5 |    3000000 |          2 |          0 |          2 |          1 |          0 |
|         4 | 09:51:46.5 |    3000000 |          0 |          0 |          0 |          1 |          1 |
|         5 | 09:51:47.5 |    3000000 |          1 |          1 |          0 |          1 |          1 |
+-----------+------------+------------+------------+------------+------------+------------+------------+
generator count ['b08df7db'] (scan num: 24)
Out[2]: ('b08df7db-5705-45c5-8e50-e528ad92cacc',)
```

_Note_: **My** soft scaler always counts for 0.1s longer than its preset time.  Note that the measurements are reported with a period of 1.0s.

**Comment by jilavsky** [comment]
Works perfectly fine. Additional information needed: how do preset time and delay interact? Is delay time inserted between two counts? That is - is delay time =0 acceptable? I tried preset =0.02 and delay =0.01 and it worked. Time stamps are difficult to figure this out.

**Comment by prjemian** [comment]
`delay=0` is acceptable, think of this as the period between starting to count the scaler.

When delay > scaler.preset_time< I expect that acquisition should occur every `delay` seconds.

The time precision reported in the table is 0.1 s (you need at least two digits to see the effects of your settings).  However, the data are reported to much higher precision.

**Comment by jilavsky** [comment]
thanks, very useful... Works great.
